algoritmo "nomeesalario"
var
nome: caractere
salario: real
inicio
//3) Crie um programa que leia o nome e o salário de um
//funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.

Escreva("Qual o seu nome? ")
Leia(nome)
Escreva("Qual o seu salário? ")
Leia(salario)

Escreva("O funcionário ", nome, " tem um salário de R$",salario, " em Junho")

fimalgoritmo