algoritmo "077leituradenomes"
var
i: inteiro
v: vetor[0..6] de caractere
inicio
//77) Faça um programa que leia 7 nomes de pessoas e guarde-os em um vetor. No
//final, mostre uma listagem com todos os nomes informados, na ordem inversa
//daquela em que eles foram informados.

enquanto ( i < 7 ) faca

escreva("Digite um nome: ")
leia(v[i])
i <- i + 1

fimenquanto

i <- 0
escreval("Aqui estão os nomes digitados: ")

enquanto ( i < 7 ) faca

escreval(v[i])
i <- i + 1

fimenquanto


fimalgoritmo