algoritmo "042contagemdefinida"
var
i, num: inteiro
inicio
//42) Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!

i <- 1
escreva("Digite um número: ")
leia(num)

enquanto (i <= num) faca
         escreva(i)
         i <- i + 1
fimenquanto
           escreva(" Acabou!")


fimalgoritmo