algoritmo "086procedimentoolamundo"
procedimento Gerador()
inicio
escreval("+-------=======------+")
escreval("      Olá, Mundo!     ")
escreval("+-------=======------+")
fimprocedimento

var

inicio
//86) Crie um programa que tenha um procedimento Gerador() que, quando chamado,
//mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
//Ex: Ao chamar Gerador() aparece:
//+-------=======------+
//Olá, Mundo!
//+-------=======------+

Gerador()

fimalgoritmo