algoritmo "087geradorpersonalizado"
procedimento Gerador(msg:caractere)
inicio

escreval("+------=======------+")
escreval(msg)
escreval("+-------=======------+")

fimprocedimento

var
inicio
//87) Crie um programa que melhore o procedimento Gerador() da questão anterior
//para que mostre uma mensagem personalizada, passada como parâmetro.
//Ex: Ao chamar Gerador("Aprendendo Portugol") aparece:
//+-------=======------+
//Aprendendo Portugol
//+-------=======------+

Gerador("Aprendendo Portugol")


fimalgoritmo